# Generated by Django 4.0.4 on 2024-08-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='Borrow date')),
                ('expected_return_date', models.DateTimeField(verbose_name='Expected return date')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual return date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_service.book')),
            ],
        ),
    ]
